"""add_has_brand_to_category

Revision ID: 0895b1ace4fd
Revises: a2ea54bcd983
Create Date: 2026-02-04 13:04:33.241469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0895b1ace4fd'
down_revision = 'a2ea54bcd983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_brand', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('has_brand')

    # ### end Alembic commands ###
