"""Add personal and archer fields to Archer

Revision ID: 11605466d127
Revises: 7a1dac1e03f3
Create Date: 2026-01-30 18:05:19.523164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11605466d127'
down_revision = '7a1dac1e03f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure any leftover temporary table from a previous failed run is removed
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_archer")

    # determine existing columns to avoid trying to add duplicates
    conn = op.get_bind()
    existing = [row[1] for row in conn.execute(sa.text("PRAGMA table_info('archer')"))]

    with op.batch_alter_table('archer', schema=None) as batch_op:
        if 'first_name' not in existing:
            batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        # add last_name as nullable initially to avoid NOT NULL issues for existing rows
        if 'last_name' not in existing:
            batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        if 'age' not in existing:
            batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        if 'bow_length' not in existing:
            batch_op.add_column(sa.Column('bow_length', sa.String(length=50), nullable=True))
        if 'draw_length' not in existing:
            batch_op.add_column(sa.Column('draw_length', sa.String(length=50), nullable=True))
        if 'bow_type' not in existing:
            batch_op.add_column(sa.Column('bow_type', sa.String(length=50), nullable=True))
        if 'notes' not in existing:
            batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
    # copy existing `name` values into `last_name` so data is preserved
    op.execute("UPDATE archer SET last_name = name WHERE last_name IS NULL")
    with op.batch_alter_table('archer', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('notes')
        batch_op.drop_column('bow_type')
        batch_op.drop_column('draw_length')
        batch_op.drop_column('bow_length')
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
