"""Add has_size, has_power, has_model to Category

Revision ID: 3f395d228456
Revises: 7bda5252ec91
Create Date: 2026-01-30 16:19:04.788634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f395d228456'
down_revision = '7bda5252ec91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_size', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_power', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_model', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('has_model')
        batch_op.drop_column('has_power')
        batch_op.drop_column('has_size')

    # ### end Alembic commands ###
