"""Add custom_fields to Category and custom_values to Product

Revision ID: 7a1dac1e03f3
Revises: 3f395d228456
Create Date: 2026-01-30 16:20:35.299839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1dac1e03f3'
down_revision = '3f395d228456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.Text(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_values', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('custom_values')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    # ### end Alembic commands ###
