"""Add field_units to Category

Revision ID: 97ef953ad47e
Revises: 0d74b713a1d1
Create Date: 2026-02-25 11:56:13.098682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ef953ad47e'
down_revision = '0d74b713a1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_units', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('field_units')

    # ### end Alembic commands ###
