"""Add password_hash to Archer model

Revision ID: 9dc9f66c218e
Revises: c4d5e6f7a8b9
Create Date: 2026-04-02 13:16:13.402335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc9f66c218e'
down_revision = 'c4d5e6f7a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archer', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
