"""fix archer_courses foreign keys

Revision ID: a2ea54bcd983
Revises: e01b12692014
Create Date: 2026-02-02 13:03:40.619579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ea54bcd983'
down_revision = 'e01b12692014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archer_courses', schema=None) as batch_op:
        batch_op.drop_constraint('archer_courses_archer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('archer_courses_archer_id_fkey', 'archer', ['archer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archer_courses', schema=None) as batch_op:
        batch_op.drop_constraint('archer_courses_archer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('archer_courses_archer_id_fkey', 'course', ['archer_id'], ['id'])

    # ### end Alembic commands ###
