"""add_categorie_to_archer

Revision ID: add_categorie_to_archer
Revises: e4ade002d968
Create Date: 2026-02-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_categorie_to_archer'
down_revision = 'e4ade002d968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archer', sa.Column('categorie', sa.String(50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archer', 'categorie')
    # ### end Alembic commands ###
