"""Add category position

Revision ID: bd57850f2f9a
Revises: 97ef953ad47e
Create Date: 2026-02-27 13:23:51.193479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd57850f2f9a'
down_revision = '97ef953ad47e'
branch_labels = None
depends_on = None


def upgrade():
    # Add column as nullable first (SQLite cannot add NOT NULL column without default)
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    conn = op.get_bind()
    # populate position with a deterministic ordering (by id)
    result = conn.execute(sa.text('SELECT id FROM category ORDER BY id'))
    ids = [row[0] for row in result]
    for idx, cid in enumerate(ids, start=1):
        conn.execute(sa.text('UPDATE category SET position = :pos WHERE id = :id'), {'pos': idx, 'id': cid})

    # now make the column non-nullable
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('position', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
